# NumPy Exercises

Tamás Gál (tamas.gal@fau.de)

The latest version of this notebook is available at [https://github.com/Asterics2020-Obelics](https://github.com/Asterics2020-Obelics/School2017/tree/master/numpy)

**Warning**: This notebook contains all the solutions. If you are currently sitting in the `NumPy` lecture, close this immediately ;-) You will now work in blank notebook, you don't need anything else!

In [1]:
import numpy as np
import numba as nb
import sys

print("Python version: {0}\n"
      "NumPy version: {1}\n"
      "numba version: {2}"
      .format(sys.version, np.__version__, nb.__version__))

Python version: 3.6.5 (default, Jun  1 2018, 14:48:24) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
NumPy version: 1.14.3
numba version: 0.38.1


In [2]:
def describe(np_obj):
    """Print some information about a NumPy object"""
    print("object type: {0}\n"
          "size: {o.size}\n"
          "ndim: {o.ndim}\n"
          "shape: {o.shape}\n"
          "dtype: {o.dtype}"
          .format(type(np_obj), o=np_obj))

In [3]:
from IPython.core.magic import register_line_magic

@register_line_magic
def shorterr(line):
    """Show only the exception message if one is raised."""
    try:
        output = eval(line)
    except Exception as e:
        print("\x1b[31m\x1b[1m{e.__class__.__name__}: {e}\x1b[0m".format(e=e))
    else:
        return output
    
del shorterr

## Exercise 1: Create a 5x5 matrix with 5's on its diagonal

```5 0 0 0 0
0 5 0 0 0
0 0 5 0 0
0 0 0 5 0
0 0 0 0 5
```

### Solution: `np.eye()`

In [4]:
np.eye(5) * 5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### Alternative solutions and further discussions

In [5]:
%timeit np.eye(500) * 5

529 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
%%timeit
a = np.eye(500)
a  *= 5

698 µs ± 16.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
%%timeit
a = np.eye(500)
np.multiply(a, 5, out=a)  # avoid creating a copy 

690 µs ± 14.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%%timeit
a = np.zeros((500, 500))
# faster on large arrays, no unnecessary multiplications
a[np.diag_indices_from(a)] = 5

513 µs ± 18.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
%timeit np.diag(np.ones(500) * 5)

408 µs ± 7.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Exercise 2: Create a random array with 10 elements and replace its largest value with 0

### Solution:

In [10]:
a = np.random.random(10)
a

array([0.93998032, 0.11973269, 0.79681713, 0.37440702, 0.06232014,
       0.83166863, 0.78647691, 0.09824825, 0.47518053, 0.64612084])

In [11]:
np.argmax(a)  # gives the index of the maximum
a[np.argmax(a)] = 0
a

array([0.        , 0.11973269, 0.79681713, 0.37440702, 0.06232014,
       0.83166863, 0.78647691, 0.09824825, 0.47518053, 0.64612084])

## Exercise 3: Create the following array

    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5


### Solution:

In [12]:
np.ones((5, 5)) * np.arange(1, 6)

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [13]:
np.ones(5)[:, np.newaxis] * np.arange(1, 6)

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

### Alternative solutions and further discussions

In [14]:
%timeit np.ones((500, 5)) * np.arange(1, 6)

13.8 µs ± 208 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
%%timeit
a = np.ones((500, 5))
np.multiply(a, np.arange(1, 6), out=a)

12.9 µs ± 287 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
%timeit np.ones(500)[:, np.newaxis] * np.arange(1, 6)

17.8 µs ± 343 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
%%timeit
a = np.empty((500, 5))
a[:] = np.arange(1, 6)

6.01 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones(5)[:, np.newaxis]  # adds a new dimension

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [20]:
np.ones(5)[:, np.newaxis].shape

(5, 1)

In [21]:
np.arange(1, 6).shape

(5,)

In [22]:
# broadcasting will turn (5, 1) and (5,) into (5, 5)
(np.ones(5)[:, np.newaxis] * np.arange(1, 6)).shape

(5, 5)

## Exercise 4: Create a checkerboard (8x8, 0s and 1s)

    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0

### Solution:

In [23]:
checkerboard = np.zeros((8, 8), dtype='i')
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

## Exercise 5: Extract the integer part of a random sample

    np.random.uniform(0, 10, 10)
    
e.g. `[23.5, 42.0, 500.3, 123.9] -> [23, 42, 500, 123]`

### Solution:

In [24]:
a = np.random.uniform(0, 10, 10)
a

array([1.81635157, 9.69170867, 9.41075471, 1.58752671, 7.14963916,
       2.78481071, 4.46037584, 5.01008261, 5.38293302, 4.87229689])

In [25]:
a - a%1

array([1., 9., 9., 1., 7., 2., 4., 5., 5., 4.])

In [26]:
np.floor(a)

array([1., 9., 9., 1., 7., 2., 4., 5., 5., 4.])

In [27]:
np.ceil(a) - 1

array([1., 9., 9., 1., 7., 2., 4., 5., 5., 4.])

In [28]:
np.trunc(a)

array([1., 9., 9., 1., 7., 2., 4., 5., 5., 4.])

In [29]:
a.astype(int)

array([1, 9, 9, 1, 7, 2, 4, 5, 5, 4])

### Further discussions

In [30]:
a = np.random.uniform(0, 10, 10000)

In [31]:
%timeit a - a%1

212 µs ± 9.07 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
%timeit np.floor(a)

43.8 µs ± 2.05 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [33]:
%timeit np.ceil(a) - 1

47.6 µs ± 1.54 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
%timeit np.trunc(a)

47.5 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [35]:
%timeit a.astype(int)  # the winner -> casting

6.19 µs ± 225 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Exercise 6: Create an array with 10 equidistant numbers between 0 and 1, excluding 0 and 1

### Solution:

In [36]:
a = np.linspace(0, 10, 11, endpoint=False)[1:]
a

array([0.90909091, 1.81818182, 2.72727273, 3.63636364, 4.54545455,
       5.45454545, 6.36363636, 7.27272727, 8.18181818, 9.09090909])

## Exercise 7: Find the value closest to a given number in an array

    a = np.random.random(10)
    target = 0.23

### Solution:

In [37]:
a = np.random.random(10)
target = 0.23
a

array([0.06991309, 0.46223431, 0.45590581, 0.94117705, 0.23632965,
       0.30774581, 0.87323518, 0.47147362, 0.56116807, 0.34130138])

In [38]:
a[np.argmin(np.abs(a - target))]

0.23632964796199774

## Exercise 8: Multiply two arrays elementwise

    a = np.random.random(1234567)
    b = np.random.random(1234567)

### Solution:

In [39]:
a = np.random.random(1234567)
b = np.random.random(1234567)

In [40]:
%time a*b

CPU times: user 5.1 ms, sys: 5.94 ms, total: 11 ms
Wall time: 9.74 ms


array([2.76232760e-01, 3.70330265e-01, 3.02549579e-04, ...,
       5.77042902e-01, 6.66688716e-03, 4.68764395e-01])

In [41]:
%time np.multiply(a, b)

CPU times: user 5.52 ms, sys: 6.12 ms, total: 11.6 ms
Wall time: 11.1 ms


array([2.76232760e-01, 3.70330265e-01, 3.02549579e-04, ...,
       5.77042902e-01, 6.66688716e-03, 4.68764395e-01])

In [42]:
%time np.multiply(a, b, out=a)

CPU times: user 3.6 ms, sys: 1.46 ms, total: 5.06 ms
Wall time: 3.12 ms


array([2.76232760e-01, 3.70330265e-01, 3.02549579e-04, ...,
       5.77042902e-01, 6.66688716e-03, 4.68764395e-01])

## Exercise 8: Calculate the cosine of 12.345.678 elements

    a = np.random.random(12345678)

### Solution:

In [43]:
a = np.random.random(12345678)

In [44]:
%time np.cos(a)

CPU times: user 145 ms, sys: 41 ms, total: 186 ms
Wall time: 191 ms


array([0.69164077, 0.86279322, 0.64387419, ..., 0.8727125 , 0.99899012,
       0.93369118])

In [45]:
%time np.cos(a, out=a)

CPU times: user 122 ms, sys: 3.72 ms, total: 125 ms
Wall time: 128 ms


array([0.69164077, 0.86279322, 0.64387419, ..., 0.8727125 , 0.99899012,
       0.93369118])

## Exercise 8: Calculate the following, with two 1.234.567 length arrays:

    a = np.random.random(1234567)
    b = np.random.random(1234567)
    
$$
c_i = \tan(a_i) \cdot b_i - a_i^{b_i}
$$

for $i \in [0, 1234566]$

### Solution:

In [46]:
a = np.random.random(1234567)
b = np.random.random(1234567)

In [47]:
def f(a, b):
    return np.tan(a) * b - a**b

In [48]:
%time f(a, b)

CPU times: user 63.1 ms, sys: 7.92 ms, total: 71 ms
Wall time: 70.1 ms


array([-0.91608905, -0.03864109, -0.47208216, ..., -0.25131989,
        0.0829329 , -0.04815672])

### What about a Python loop?

In [49]:
def silly_func(a, b):
    c = np.empty_like(a)
    for i in range(len(a)):
        c[i] = np.tan(a[i]) * b[i] - np.power(a[i], b[i])
    return c

In [50]:
%time silly_func(a, b)

CPU times: user 7.4 s, sys: 95.9 ms, total: 7.5 s
Wall time: 7.7 s


array([-0.91608905, -0.03864109, -0.47208216, ..., -0.25131989,
        0.0829329 , -0.04815672])

### Let's JIT it with `numba`!

In [51]:
@nb.jit
def silly_func(a, b):
    c = np.empty_like(a)
    for i in range(len(a)):
        c[i] = np.tan(a[i]) * b[i] - np.power(a[i], b[i])
    return c

In [52]:
%time silly_func(a, b)  # first execution includes the compilation!

CPU times: user 327 ms, sys: 28.1 ms, total: 355 ms
Wall time: 437 ms


array([-0.91608905, -0.03864109, -0.47208216, ..., -0.25131989,
        0.0829329 , -0.04815672])

In [53]:
%time silly_func(a, b)  # the second is pure LLVM optimised code

CPU times: user 55 ms, sys: 6.33 ms, total: 61.4 ms
Wall time: 65.2 ms


array([-0.91608905, -0.03864109, -0.47208216, ..., -0.25131989,
        0.0829329 , -0.04815672])

In [54]:
@nb.jit
def silly_func_mutating_a(a, b):
    for i in range(len(a)):
        a[i] = np.tan(a[i]) * b[i] - np.power(a[i], b[i])

In [55]:
%time silly_func_mutating_a(a, b);  # first execution includes the compilation!

CPU times: user 148 ms, sys: 5.62 ms, total: 153 ms
Wall time: 160 ms


In [56]:
%time silly_func_mutating_a(a, b);  # the second is pure LLVM optimised code

CPU times: user 30.4 ms, sys: 409 µs, total: 30.8 ms
Wall time: 31.7 ms


Summary (running them once on my 2017 MacBook Air 17: 2.2GHz i7, numbers may vary in the notebook outputs above):
- **~60ms** (numpy)
- **~7000ms** (Python)
- **~160ms** (numba, inc. JIT comp.)
- **~50ms** (numba, JIT)
- **~140ms** (reusing `a`, numba, inc. JIT comp.)
- **~25ms** (reusing `a`, numba, JIT)

## Acknowledgements
![](images/eu_asterics.png)

This tutorial was supported by the H2020-Astronomy ESFRI and Research Infrastructure Cluster (Grant Agreement number: 653477).