# Nearest Points Exercise

Tamás Gál (tamas.gal@fau.de)

The latest version of this notebook is available at [https://github.com/Asterics2020-Obelics](https://github.com/Asterics2020-Obelics/School2017/tree/master/numpy)

In [1]:
import numpy as np
import sys

print("Python version: {0}\n"
      "NumPy version: {1}"
      .format(sys.version, np.__version__))

Python version: 3.6.5 (default, Jun  1 2018, 14:48:24) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
NumPy version: 1.14.3


## Given an array of points (in 3D), find the nearest point for each one.

In [2]:
N = 500
n_dims = 3
points = np.random.random((N, n_dims))
points

array([[0.52682391, 0.84736992, 0.68428599],
       [0.00342933, 0.55981111, 0.1826532 ],
       [0.60919571, 0.78728847, 0.12705444],
       ...,
       [0.05618889, 0.1495999 , 0.14557865],
       [0.64582629, 0.58587899, 0.52161598],
       [0.14804983, 0.49087426, 0.35089677]])

### Solution

In [3]:
N = 4
n_dims = 3
points = np.random.random((N, n_dims))
points

array([[0.07678683, 0.87280216, 0.24566237],
       [0.21943355, 0.63271636, 0.77344128],
       [0.1216955 , 0.44489452, 0.08678564],
       [0.59164763, 0.09284068, 0.53764511]])

In [4]:
distances = np.sum((points.reshape(N, 1, n_dims) - points)**2, axis=2)
distances[np.diag_indices_from(distances)] = np.inf
np.argmin(distances, axis=1)

array([2, 0, 0, 1])

### Discussion

In [5]:
points

array([[0.07678683, 0.87280216, 0.24566237],
       [0.21943355, 0.63271636, 0.77344128],
       [0.1216955 , 0.44489452, 0.08678564],
       [0.59164763, 0.09284068, 0.53764511]])

In [6]:
points.shape

(4, 3)

In [7]:
reshaped_points = points.reshape(N, 1, n_dims)
reshaped_points

array([[[0.07678683, 0.87280216, 0.24566237]],

       [[0.21943355, 0.63271636, 0.77344128]],

       [[0.1216955 , 0.44489452, 0.08678564]],

       [[0.59164763, 0.09284068, 0.53764511]]])

In [8]:
reshaped_points.shape

(4, 1, 3)

In [9]:
differences = reshaped_points - points
differences

array([[[ 0.        ,  0.        ,  0.        ],
        [-0.14264672,  0.2400858 , -0.52777891],
        [-0.04490867,  0.42790764,  0.15887673],
        [-0.5148608 ,  0.77996148, -0.29198274]],

       [[ 0.14264672, -0.2400858 ,  0.52777891],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.09773805,  0.18782183,  0.68665564],
        [-0.37221408,  0.53987568,  0.23579617]],

       [[ 0.04490867, -0.42790764, -0.15887673],
        [-0.09773805, -0.18782183, -0.68665564],
        [ 0.        ,  0.        ,  0.        ],
        [-0.46995213,  0.35205385, -0.45085947]],

       [[ 0.5148608 , -0.77996148,  0.29198274],
        [ 0.37221408, -0.53987568, -0.23579617],
        [ 0.46995213, -0.35205385,  0.45085947],
        [ 0.        ,  0.        ,  0.        ]]])

In [10]:
print(reshaped_points.shape, " - ", points.shape, " => ", differences.shape)

(4, 1, 3)  -  (4, 3)  =>  (4, 4, 3)


In [11]:
distances = np.sum(differences**2, axis=2)
distances

array([[0.        , 0.35653986, 0.21036355, 0.95867548],
       [0.35653986, 0.        , 0.51632574, 0.48560891],
       [0.21036355, 0.51632574, 0.        , 0.54807118],
       [0.95867548, 0.48560891, 0.54807118, 0.        ]])

In [12]:
distances.shape

(4, 4)

In [13]:
distances

array([[0.        , 0.35653986, 0.21036355, 0.95867548],
       [0.35653986, 0.        , 0.51632574, 0.48560891],
       [0.21036355, 0.51632574, 0.        , 0.54807118],
       [0.95867548, 0.48560891, 0.54807118, 0.        ]])

In [14]:
# get rid of self-distances first ;)
distances[np.diag_indices_from(distances)] = np.inf

In [15]:
distances

array([[       inf, 0.35653986, 0.21036355, 0.95867548],
       [0.35653986,        inf, 0.51632574, 0.48560891],
       [0.21036355, 0.51632574,        inf, 0.54807118],
       [0.95867548, 0.48560891, 0.54807118,        inf]])

In [16]:
nearest_points = np.argmin(distances, axis=1)
nearest_points

array([2, 0, 0, 1])

### Comparing to `scikit-learn`

In [17]:
nearest_points

array([2, 0, 0, 1])

In [18]:
from sklearn.neighbors import NearestNeighbors
_, indices = NearestNeighbors().fit(points).kneighbors(points, 2)
indices[:, 1]

array([2, 0, 0, 1])

In [19]:
%timeit _, indices = NearestNeighbors().fit(points).kneighbors(points, 2)

152 µs ± 4.25 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
%%timeit
distances = np.sum((points.reshape(N, 1, n_dims) - points)**2, axis=2)
distances[np.diag_indices_from(distances)] = np.inf
np.argmin(distances, axis=1)

35.9 µs ± 1.36 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### Our implementation is faster just because of the function call overhead of scikit-learn. Try bigger `N`s and see how they actually compare to each other.